# Generated by Django 3.2 on 2021-05-10 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('user', '0001_initial'),
        ('medicalrecord', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField()),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Appointment'), (1, 'Feedback'), (2, 'Chat'), (3, 'Medicalrecord'), (4, 'Doctor Review')], default=0)),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('feedback_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('feedback_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
                ('medicalrecord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalrecord.medicalrecords')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('replied_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('replied_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.thread')),
            ],
            options={
                'verbose_name': 'Nofitication',
                'verbose_name_plural': 'Nofitications',
            },
        ),
    ]
