# Generated by Django 3.2.3 on 2021-09-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Appt'), (1, 'Review'), (2, 'Chat'), (3, 'Record')], default=0),
        ),
    ]
