# Generated by Django 3.2.3 on 2021-12-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='replied_chat',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Appt'), (1, 'Review'), (2, 'Record')], default=0),
        ),
    ]
