# Generated by Django 3.2.3 on 2022-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20211215_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='feedback_doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='feedback_patient',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='medicalrecord',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='replied_appointment',
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('appt_cancelation', 'Appt Cancelation'), ('chat', 'Chat'), ('review', 'Review')], max_length=25, null=True),
        ),
    ]
