# Generated by Django 3.2.3 on 2022-03-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20220325_1332'),
        ('notification', '0005_auto_20220330_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='appt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment'),
        ),
    ]
