# Generated by Django 3.2.3 on 2021-09-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleattchment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipleattach', to='chat.chatmessage', verbose_name='Message'),
        ),
    ]
