# Generated by Django 3.2.3 on 2021-12-01 10:48

import chat.models
import chat.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleattchment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_att_dir, validators=[chat.validators.attachment_valid_size, django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'tiff', 'tif', 'bmp', 'pdf'])]),
        ),
    ]
