# Generated by Django 3.2 on 2021-05-10 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_appt_time', models.DurationField(blank=True, null=True)),
                ('end_appt_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed'), ('PATIENT_CANCELED', 'Patient_Canceled'), ('DOCTOR_CANCELED', 'Doctor_Canceled')], default='PENDING', max_length=50)),
                ('feedback_status', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('appt_date', models.DateField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentConditionThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('farsi_name', models.CharField(blank=True, max_length=128)),
                ('pashto_name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Condition Thread',
                'verbose_name_plural': 'Condition Threads',
            },
        ),
        migrations.CreateModel(
            name='DaySchedulePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_duration', models.DurationField(blank=True, null=True)),
                ('start_day_time', models.DurationField(blank=True, null=True)),
                ('end_day_time', models.DurationField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_by', to='user.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='Comments')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('overall_experience', models.CharField(choices=[('BAD', 'GOOD'), ('GOOD', 'BEST')], default='GOOD', max_length=32)),
                ('doctor_checkup', models.CharField(choices=[('BAD', 'GOOD'), ('GOOD', 'BEST')], default='GOOD', max_length=32)),
                ('staff_behavior', models.CharField(choices=[('BAD', 'GOOD'), ('GOOD', 'BEST')], default='GOOD', max_length=32)),
                ('clinic_environment', models.CharField(choices=[('BAD', 'GOOD'), ('GOOD', 'BEST')], default='GOOD', max_length=32)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='appointment.appointment')),
            ],
            options={
                'verbose_name': 'Appoinment Feedback',
                'verbose_name_plural': 'Appointments Feedback',
            },
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(blank=True, max_length=120, null=True)),
                ('rtl_week_day', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='appointment.feedback')),
            ],
            options={
                'verbose_name': 'Feedback Reply',
                'verbose_name_plural': 'Feedback Replies',
            },
        ),
        migrations.CreateModel(
            name='DeactivatedApptSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_appt_time', models.DurationField(blank=True, null=True)),
                ('end_appt_time', models.DurationField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.clinic')),
                ('day_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.dayschedulepattern')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='dayschedulepattern',
            name='week_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.weekdays'),
        ),
        migrations.CreateModel(
            name='ApptQrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_img', models.ImageField(blank=True, null=True, upload_to='appt_qr')),
                ('appt_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='appointment.appointment')),
            ],
            options={
                'verbose_name': 'Appointment Qr Code',
                'verbose_name_plural': 'Appointments Qr Code',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='condition_threaded',
            field=models.ManyToManyField(blank=True, to='appointment.AppointmentConditionThread'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='day_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.dayschedulepattern'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='relative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.relative'),
        ),
    ]
