# Generated by Django 3.2.3 on 2021-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210610_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentConditionThread',
            new_name='ApptConditionTreat',
        ),
        migrations.AlterModelOptions(
            name='apptconditiontreat',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='condition_threaded',
        ),
        migrations.AddField(
            model_name='appointment',
            name='condition_treated',
            field=models.ManyToManyField(blank=True, to='appointment.ApptConditionTreat'),
        ),
    ]
