# Generated by Django 3.2.3 on 2021-06-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20210610_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='clinic_environment',
            field=models.CharField(choices=[('Good', 'Good'), ('Better', 'Better')], default='Good', max_length=32),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='doctor_checkup',
            field=models.CharField(choices=[('Good', 'Good'), ('Better', 'Better')], default='Good', max_length=32),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_experience',
            field=models.CharField(choices=[('Good', 'Good'), ('Better', 'Better')], default='Good', max_length=32),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='staff_behavior',
            field=models.CharField(choices=[('Good', 'Good'), ('Better', 'Better')], default='Good', max_length=32),
        ),
    ]
