# Generated by Django 3.2.3 on 2021-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20210610_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptconditiontreat',
            name='farsi_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='apptconditiontreat',
            name='pashto_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
