# Generated by Django 3.2.3 on 2021-12-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20210610_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
