# Generated by Django 3.2.3 on 2022-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_patient_submit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
