# Generated by Django 3.2.3 on 2022-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20220324_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_patient_submit',
            field=models.BooleanField(default=False),
        ),
    ]
