# Generated by Django 3.2.3 on 2022-03-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20210808_1758'),
        ('appointment', '0008_alter_feedback_is_patient_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.dayschedulepattern'),
        ),
    ]
