# Generated by Django 3.2.3 on 2021-12-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
