# Generated by Django 3.2 on 2021-05-10 07:02

from django.db import migrations, models
import django.db.models.deletion
import medicalrecord.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSharingPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
                ('relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.relative')),
            ],
            options={
                'verbose_name': 'File Sharing',
                'verbose_name_plural': 'File Sharings',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('file', models.FileField(blank=True, null=True, upload_to=medicalrecord.models.upload_file_path)),
                ('doctor_access', models.BooleanField(default=True, verbose_name='Doctor')),
                ('general_access', models.BooleanField(default=True, verbose_name='General')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='user.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalrecord.filesharingpatient')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
            },
        ),
    ]
