# Generated by Django 3.2.3 on 2021-05-25 08:53

from django.db import migrations, models
import medicalrecord.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='file',
            field=models.FileField(default='1', upload_to=medicalrecord.models.upload_file_path),
            preserve_default=False,
        ),
    ]
