# Generated by Django 3.2.3 on 2021-08-13 09:20

from django.db import migrations, models
import django.db.models.deletion
import medicalrecord.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0002_alter_medicalrecords_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecords',
            name='file',
        ),
        migrations.CreateModel(
            name='MedicalRecordFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=medicalrecord.models.upload_file_path)),
                ('medidcal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalrecord.medicalrecords')),
            ],
        ),
    ]
