# Generated by Django 3.2.3 on 2021-08-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0003_auto_20210813_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesharingpatient',
            options={'verbose_name': 'Patient File', 'verbose_name_plural': 'Patient File Shares'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecordfile',
            options={'verbose_name': 'Medical Record File', 'verbose_name_plural': 'Medical Record Files'},
        ),
        migrations.RenameField(
            model_name='medicalrecordfile',
            old_name='medidcal_record',
            new_name='medical_record',
        ),
    ]
