# Generated by Django 3.2.3 on 2021-12-01 11:15

import django.core.validators
from django.db import migrations, models
import medicalrecord.models
import medicalrecord.validators


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0006_auto_20211201_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordfile',
            name='file',
            field=models.FileField(upload_to=medicalrecord.models.upload_file_path, validators=[medicalrecord.validators.attachment_valid_size, django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'tiff', 'tif', 'bmp', 'pdf', 'docx', 'odt', 'txt', 'zip'])]),
        ),
    ]
