# Generated by Django 3.2.3 on 2021-12-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_avatar'),
        ('medicalrecord', '0007_alter_medicalrecordfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecords',
            name='relative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.relative'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient'),
        ),
        migrations.DeleteModel(
            name='FileSharingPatient',
        ),
    ]
