# Generated by Django 3.2.3 on 2021-06-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_doctor_professional_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Relative', 'Relative'), ('Admin', 'Admin'), ('Blogger', 'Blogger'), ('HealthMinistry', 'Healthministry'), ('AdminPlus', 'Adminplus')], default='Patient', max_length=50),
        ),
    ]
