# Generated by Django 3.2.3 on 2021-06-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_type',
            field=models.CharField(choices=[('Volunteer', 'Volenteer'), ('Onpremise', 'Onpremise'), ('Onlinecunsultant', 'Onlineconsultant')], default='Volunteer', max_length=50),
        ),
    ]
