# Generated by Django 3.2.3 on 2021-06-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_doctor_doctor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=16)),
                ('farsi_relation', models.CharField(max_length=32, null=True)),
                ('pashto_relation', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='relative',
            name='rel',
        ),
        migrations.DeleteModel(
            name='RelativeRelationships',
        ),
        migrations.AddField(
            model_name='relative',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.relativerelation'),
        ),
    ]
