# Generated by Django 3.2.3 on 2021-06-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210610_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeServiceSchedule',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.doctor')),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_free_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
