# Generated by Django 3.2.3 on 2021-08-10 07:28

import django.core.validators
from django.db import migrations, models
import user.models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=user.models.upload_user_avatar, validators=[user.validators.avatar_size, django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'tiff', 'tif', 'bmp'], message='Invalid Image extension.')]),
        ),
    ]
