# Generated by Django 3.2.3 on 2021-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='share_record_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relative',
            name='share_record_to_all',
            field=models.BooleanField(default=True),
        ),
    ]
