# Generated by Django 3.2.3 on 2022-03-10 05:51

import django.core.validators
from django.db import migrations, models
import user.models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20211205_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_user_avatar, validators=[user.validators.avatar_size, django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'tiff', 'tif', 'bmp'], message='Invalid Image extension.')]),
        ),
    ]
