# Generated by Django 3.2.3 on 2022-03-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='operation',
        ),
    ]
