# Generated by Django 3.2.3 on 2022-03-15 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_otpverification_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 20, 45, 40, 816142)),
        ),
    ]
