# Generated by Django 3.2.3 on 2022-03-15 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_otpverification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 16, 27, 6, 399570, tzinfo=utc)),
        ),
    ]
