# Generated by Django 3.2.3 on 2022-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_otpverification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
