# Generated by Django 3.2.3 on 2022-03-15 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_otpverification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 21, 39, 50, 805468)),
        ),
    ]
