# Generated by Django 3.2.3 on 2022-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_otpverification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_profile_on_progress',
            field=models.BooleanField(default=False),
        ),
    ]
