# Generated by Django 3.2.3 on 2021-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_timestamp'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='speciality',
        ),
        migrations.AddField(
            model_name='disease',
            name='speciality',
            field=models.ManyToManyField(related_name='disease', to='user.Speciality'),
        ),
    ]
