# Generated by Django 3.2.3 on 2021-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_timestamp'),
        ('doctor', '0002_auto_20210528_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('farsi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pashto_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disease', models.ManyToManyField(related_name='symptom', to='user.Speciality')),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
            },
        ),
    ]
