# Generated by Django 3.2.3 on 2021-06-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('farsi_name', models.CharField(max_length=255)),
                ('pashto_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='award',
            name='award_description',
        ),
        migrations.RemoveField(
            model_name='award',
            name='award_description_rtl',
        ),
        migrations.RemoveField(
            model_name='education',
            name='rtl_degree',
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='disease',
            field=models.ManyToManyField(related_name='symptom', to='doctor.Disease'),
        ),
        migrations.CreateModel(
            name='EducationDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('farsi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pashto_name', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.degreetype')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.educationdegree'),
        ),
    ]
