# Generated by Django 3.2.3 on 2021-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20210612_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
