# Generated by Django 3.2.3 on 2021-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_clinic_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='rtl_clinic_name',
            field=models.CharField(max_length=255),
        ),
    ]
