# Generated by Django 3.2.3 on 2022-03-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220310_1021'),
        ('doctor', '0006_auto_20210808_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.city'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.district'),
        ),
    ]
